CLEAR="$(tput sgr0)"
YELLOW="$(tput bold)$(tput setaf 3)"

post_install() {
    printf "%sNOTE%s: Add yourself to group \"informant\" to avoid the need for sudo\n" "$YELLOW" "$CLEAR"
}

post_upgrade() {
    post_install
    #new_ver=$1
    old_ver=$2
    if [[ $old_ver =~ ^0\.[0123]\.* ]]; then
        mv /var/cache/informant.dat /var/lib/informant.dat
        printf "%sNOTE%s: This update moves the location of the save file.\n/var/cache/informant.dat is now /var/lib/informant.dat, and cache data is saved in /var/cache/informant/.\nYou should not need to re-read old items.\n" "$YELLOW" "$CLEAR"
    fi
    if [[ $old_ver =~ ^0\.[01]\.* ]]; then
        printf "%sWARNING%s: This update changes the format of the save file, you will need to re-read all news items.\n" "$YELLOW" "$CLEAR"
    fi
}
